### ISSUE TITLE
Version endpoint should identify the exact source code revision

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-web#183]
We have an endpoint to see the version of the gitbase-playground i.e at 

```
$ curl https://gitbase-playground-staging.srcd.run/version
```

but it is ambiguous. It should identify the exact source code revision used for the build./

Expected outcome:
 - an identifier that points to the uniq revising of the code, used for this build i.e 
   `v0.1.0`  or  it's sha1 `9a885b0`

Current outcome:

 - ```
    {"status":200,"data":{"version":"master"}}
    ````

With current behaviour it is impossible to identify the revision i.e to get the same version locally and reproduce a bug.

**Comment by carlosms** [comment]
I created a PR in the CI repo for this: https://github.com/src-d/ci/pull/82

There  is a minor problem. The version name for this project will have the `-dirty` suffix when it's not a tag build. This is because of how we do go-bindata, it makes changes to a file in git (see #24).

**Comment by bzz** [comment]
82 is merged now, what would be the next steps?

**Comment by carlosms** [comment]
We just need to force a new deployment doing a new commit to master.
Conveniently, I just found a bug in the makefile, #201, so we can use that one :D

**Comment by bzz** [comment]
Shall we merge #201 and deploy?

**Comment by carlosms** [comment]
#201 merged.
We still need to:
- update gitbase to 0.15.0 (#204) to report its version
- fix #203, until then there are changes after `dep ensure` and the version reported has the suffix `-dirty`.

**Comment by bzz** [comment]
Great, all looks ready to be merged and :shipit: !

**Comment by bzz** [comment]
https://gitbase-playground-staging.srcd.run/version
```
{"status":200,"data":{"version":"dev-558c67b","bblfsh":"v2.5.0","gitbase":"8.0.11-undefined"}}
```
🎉
