### ISSUE TITLE
Latest release v0.1.3 throws TypeError 

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase-web#226]
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

Behaviour: click "Run Query" and nothing happens

Developer Tool console:

```
Uncaught TypeError: window.AbortController is not a constructor
    at t.value (App.js:215)
    at t.value (App.js:261)
    at Object.o (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
    at c (react-dom.production.min.js:20)
    at p (react-dom.production.min.js:22)
    at m (react-dom.production.min.js:22)
    at f (react-dom.production.min.js:21)
    at v (react-dom.production.min.js:24)
```

**Comment by eiso** [comment]
I spent a few minutes investigating this and learned that the AbortController (https://developer.mozilla.org/en-US/docs/Web/API/AbortController) is an experimental feature only enabled since Google Chrome 66. When I upgraded to the latest stable version (68.0.3440.106 (Official Build) (64-bit)) everything worked. 

@bzz what are our browser compatibility guidelines?

**Comment by carlosms** [comment]
We are only using the polyfill in the tests setup, not in the application code itself. It should be easy to add to the browser code. From [PR #217](https://github.com/src-d/gitbase-web/pull/217#issue-208887227):

> The abort-controller polyfill is used only for the jest tests. All major browsers apparently support AbortCotroller (https://caniuse.com/#search=fetch), and for example for older IE this PR does not break compatibility because it doesn't support fetch API either, which we already use.

About
> seems like some extra work be needed here in order to make it work in IE11

I think you got IE and Edge mixed there. IE11 latest release is from 2013, I don't think we want to support that! Edge supports fetch and abort controller.

**Comment by bzz** [comment]
Thank you for explaining, makes sense.

> I think you got IE and Edge mixed there

✅ updated the description above
