### ISSUE TITLE
Current master is failing in CI

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gitbase-web#236]
Current `master` is failing in the CI
https://travis-ci.org/src-d/gitbase-web/branches

![image](https://user-images.githubusercontent.com/2437584/45561735-bb0abf80-b848-11e8-82c1-5b153b7cba7b.png)

Latest build when this PR was created: [build#514](https://travis-ci.org/src-d/gitbase-web/builds/428577202)

**Comment by smacker** [comment]
It happens because of https://github.com/src-d/gitbase-web/issues/233 most probably.
We use the latest gitbase in CI and the breaking change was merged and released.

**Comment by carlosms** [comment]
Fixed in #233. The problem was triggered because the gitbase RCs docker images are published as latest.
