### ISSUE TITLE
Do not highlight "language" in queries

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/gitbase-web#239]
We are using CodeMirror, MySQL mode.

It [includes "language" in the list of keywords](https://github.com/codemirror/CodeMirror/blob/master/mode/sql/sql.js#L316) so it is highlighted in the editor. This is very annoying: we have the same function to find the language of a blob.
MySQL indeed lists "language" in the official list of keywords.

I suggest to hack as always:

```js
delete CodeMirror.mimeModes["text/x-mysql"].keywords.language;
```

Tested - works. I can do a PR if needed.

**Comment by carlosms** [comment]
If we are going to modify the keywords, I think it would be more useful to include all the gitbase functions.

Closing in favor of #319.
