### ISSUE TITLE
Add a modal help dialog with keyboard shorcuts

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-web#293]
This will be a small button that will open a simple modal window with the keyboard shortcuts:
- ctrl+enter to run the query
- ctrl+space to autocomplete.

**Comment by carlosms** [comment]
Of course! :)
I was thinking of a very small icon with `?` or a keyboard symbol. Either next to "Help", or to the left of "Export". But any input is more than welcome.

**Comment by ricardobaeta** [comment]
I would go with a keyboard symbol next to help. What kind of icon-font we could use, or should I provide an icon?

**Comment by ricardobaeta** [comment]
Hi @carlosms :)

What do you think?

![image](https://user-images.githubusercontent.com/1746146/49809249-b2018f80-fd5e-11e8-8976-842a8a481709.png)

**Comment by carlosms** [comment]
Great, thank you
