### ISSUE TITLE
Getting error when click on UAST button

### ISSUE THREAD

**Issue by gregkonushev-okta** [src-d/gitbase-web#304]
query that I used: 
`SELECT file_path, uast(blob_content, language(file_path)) FROM files where file_path like '%.java' limit 5;
`
results in this error and blank window:
![image](https://user-images.githubusercontent.com/42911834/51417180-b2493380-1b31-11e9-9eb3-81d2e34da10c.png)

**Comment by gregkonushev-okta** [comment]
When I run the same query but for '%.py' or '%.js' files it works just fine.

**Comment by se7entyse7en** [comment]
Hi @gregkonushev-okta, thanks for opening the issue!

What version of `gitbase-web` are you using? I tried to reproduce the bug but I failed to. Would you mind sharing more informations? Could you try the same query by trying it using the mysql client directly?

**Comment by gregkonushev-okta** [comment]
Versions:
srcd cli version: v0.8.0
docker version: 1.39
srcd daemon version: v0.8.0
srcd/gitbase-web:v0.5.0
srcd/gitbase:v0.18.0
bblfsh/bblfshd:v2.11.0-drivers
@se7entyse7en After running in mysql client:
`gitbase> SELECT file_path, uast(blob_content, language(file_path)) FROM files where file_path like '%.java' limit 5;
rpc error: code = Internal desc = grpc: error while marshaling: proto: invalid UTF-8 string`

**Comment by gregkonushev-okta** [comment]
I believe it's a frontend issue as I am getting response back from server:
![image](https://user-images.githubusercontent.com/42911834/51627853-416e9680-1ef8-11e9-97ed-a183b4385f15.png)

**Comment by smacker** [comment]
Is it possible to share the repository which has the file that produces this error with us? 

It is a frontend bug for sure but it would be great if we could reproduce it. For that, we need source code that produces UAST which breaks frontend.

Thank you!
