### ISSUE TITLE
Running a query containing the `REGEXP` function with an invalid pattern breaks

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/gitbase-web#307]
If the query contains the `REGEXP` function and the pattern is invalid, then the server stops working and doesn't recover anymore. At the first run it answers:

<img width="461" alt="screenshot 2019-01-23 at 20 30 06" src="https://user-images.githubusercontent.com/5599208/51631709-b324ff80-1f4d-11e9-9767-b61c11d5b57b.png">

From the second run and on it answers:

<img width="616" alt="screenshot 2019-01-23 at 20 29 29" src="https://user-images.githubusercontent.com/5599208/51631739-c2a44880-1f4d-11e9-8ed6-e17bd3c9d46e.png">

From the log it seems that the bug is caused by how the wrong pattern is handled in `gitbase`. Here's the log:

<img width="1440" alt="screenshot 2019-01-23 at 20 32 26" src="https://user-images.githubusercontent.com/5599208/51631824-0434f380-1f4e-11e9-960c-c6b082c6bbb0.png">

**Comment by smacker** [comment]
it's a panic in gitbase. You better open an issue in https://github.com/src-d/gitbase
Thanks!

**Comment by carlosms** [comment]
Closing since this is already tracked in https://github.com/src-d/gitbase/issues/682
