### ISSUE TITLE
Remove GITBASE_UNSTABLE_SQUASH_ENABLE

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-web#355]
As detected by @mcarmonaa:

> Also GITBASE_UNSTABLE_SQUASH_ENABLE: "true" can be removed, it's the default behaviour since gitbase v0.14.0.

**Comment by mcarmonaa** [comment]
I already sent a PR for this #348

**Comment by carlosms** [comment]
Fixed by #348.
