### ISSUE TITLE
Update docker-compose for gitbase 0.19

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-web#356]
Reported by @mcarmonaa:

> I've got errors from the docker-compose file:
> ```
> $ GITBASEPG_REPOS_FOLDER=repos docker-compose up
> ERROR: Named volume "repos:/opt/repos:rw" is used in service "gitbase" but no declaration was found in the volumes section.
> ```
> It has to be modified to use gitbase version v0.19.0-rc1.

**Comment by mcarmonaa** [comment]
I explained this wrong, sorry. The error isn't related with gitbase image version that was an independent comment. Probably it's because docker needs absolute paths for volumes.

**Comment by carlosms** [comment]
Yup, this needs be used as
`GITBASEPG_REPOS_FOLDER=./repos docker-compose up`

I'm closing this one as it's not a bug on gitbase-web.
