### ISSUE TITLE
Collapsing UAST elements makes code text dissapear

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-web#369]
Tested on chrome and firefox. I think this can be caused by the latest update of uast-viewer in #364.

![a](https://user-images.githubusercontent.com/1469173/54118579-483f6300-43eb-11e9-92cf-feb7950b30df.gif)

**Comment by smacker** [comment]
can't reproduce. with both `yarn start` & `make serve`.
It also works fine for me on staging: https://gitbase-playground-staging.srcd.run/

**Comment by carlosms** [comment]
I've tried again I I can't reproduce it either, so I was probably using outdated npm dependencies. Sorry!
